/*
NRF NFManagement Service

NRF NFManagement Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.2.0-alpha.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TsctsfInfo Information of a TSCTSF NF Instance
type TsctsfInfo struct {
	// A map (list of key-value pairs) where a valid JSON string serves as key
	SNssaiInfoList *map[string]SnssaiTsctsfInfoItem `json:"sNssaiInfoList,omitempty"`
	ExternalGroupIdentifiersRanges *[]IdentityRange `json:"externalGroupIdentifiersRanges,omitempty"`
}

// NewTsctsfInfo instantiates a new TsctsfInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTsctsfInfo() *TsctsfInfo {
	this := TsctsfInfo{}
	return &this
}

// NewTsctsfInfoWithDefaults instantiates a new TsctsfInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTsctsfInfoWithDefaults() *TsctsfInfo {
	this := TsctsfInfo{}
	return &this
}

// GetSNssaiInfoList returns the SNssaiInfoList field value if set, zero value otherwise.
func (o *TsctsfInfo) GetSNssaiInfoList() map[string]SnssaiTsctsfInfoItem {
	if o == nil || o.SNssaiInfoList == nil {
		var ret map[string]SnssaiTsctsfInfoItem
		return ret
	}
	return *o.SNssaiInfoList
}

// GetSNssaiInfoListOk returns a tuple with the SNssaiInfoList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TsctsfInfo) GetSNssaiInfoListOk() (*map[string]SnssaiTsctsfInfoItem, bool) {
	if o == nil || o.SNssaiInfoList == nil {
		return nil, false
	}
	return o.SNssaiInfoList, true
}

// HasSNssaiInfoList returns a boolean if a field has been set.
func (o *TsctsfInfo) HasSNssaiInfoList() bool {
	if o != nil && o.SNssaiInfoList != nil {
		return true
	}

	return false
}

// SetSNssaiInfoList gets a reference to the given map[string]SnssaiTsctsfInfoItem and assigns it to the SNssaiInfoList field.
func (o *TsctsfInfo) SetSNssaiInfoList(v map[string]SnssaiTsctsfInfoItem) {
	o.SNssaiInfoList = &v
}

// GetExternalGroupIdentifiersRanges returns the ExternalGroupIdentifiersRanges field value if set, zero value otherwise.
func (o *TsctsfInfo) GetExternalGroupIdentifiersRanges() []IdentityRange {
	if o == nil || o.ExternalGroupIdentifiersRanges == nil {
		var ret []IdentityRange
		return ret
	}
	return *o.ExternalGroupIdentifiersRanges
}

// GetExternalGroupIdentifiersRangesOk returns a tuple with the ExternalGroupIdentifiersRanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TsctsfInfo) GetExternalGroupIdentifiersRangesOk() (*[]IdentityRange, bool) {
	if o == nil || o.ExternalGroupIdentifiersRanges == nil {
		return nil, false
	}
	return o.ExternalGroupIdentifiersRanges, true
}

// HasExternalGroupIdentifiersRanges returns a boolean if a field has been set.
func (o *TsctsfInfo) HasExternalGroupIdentifiersRanges() bool {
	if o != nil && o.ExternalGroupIdentifiersRanges != nil {
		return true
	}

	return false
}

// SetExternalGroupIdentifiersRanges gets a reference to the given []IdentityRange and assigns it to the ExternalGroupIdentifiersRanges field.
func (o *TsctsfInfo) SetExternalGroupIdentifiersRanges(v []IdentityRange) {
	o.ExternalGroupIdentifiersRanges = &v
}

func (o TsctsfInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SNssaiInfoList != nil {
		toSerialize["sNssaiInfoList"] = o.SNssaiInfoList
	}
	if o.ExternalGroupIdentifiersRanges != nil {
		toSerialize["externalGroupIdentifiersRanges"] = o.ExternalGroupIdentifiersRanges
	}
	return json.Marshal(toSerialize)
}

type NullableTsctsfInfo struct {
	value *TsctsfInfo
	isSet bool
}

func (v NullableTsctsfInfo) Get() *TsctsfInfo {
	return v.value
}

func (v *NullableTsctsfInfo) Set(val *TsctsfInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableTsctsfInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableTsctsfInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTsctsfInfo(val *TsctsfInfo) *NullableTsctsfInfo {
	return &NullableTsctsfInfo{value: val, isSet: true}
}

func (v NullableTsctsfInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTsctsfInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


