/*
NRF NFDiscovery Service

NRF NFDiscovery Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.2.0-alpha.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// HssInfo Information of an HSS NF Instance
type HssInfo struct {
	// Identifier of a group of NFs.
	GroupId *string `json:"groupId,omitempty"`
	ImsiRanges *[]ImsiRange `json:"imsiRanges,omitempty"`
	ImsPrivateIdentityRanges *[]IdentityRange `json:"imsPrivateIdentityRanges,omitempty"`
	ImsPublicIdentityRanges *[]IdentityRange `json:"imsPublicIdentityRanges,omitempty"`
	MsisdnRanges *[]IdentityRange `json:"msisdnRanges,omitempty"`
}

// NewHssInfo instantiates a new HssInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHssInfo() *HssInfo {
	this := HssInfo{}
	return &this
}

// NewHssInfoWithDefaults instantiates a new HssInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHssInfoWithDefaults() *HssInfo {
	this := HssInfo{}
	return &this
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *HssInfo) GetGroupId() string {
	if o == nil || o.GroupId == nil {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HssInfo) GetGroupIdOk() (*string, bool) {
	if o == nil || o.GroupId == nil {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *HssInfo) HasGroupId() bool {
	if o != nil && o.GroupId != nil {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *HssInfo) SetGroupId(v string) {
	o.GroupId = &v
}

// GetImsiRanges returns the ImsiRanges field value if set, zero value otherwise.
func (o *HssInfo) GetImsiRanges() []ImsiRange {
	if o == nil || o.ImsiRanges == nil {
		var ret []ImsiRange
		return ret
	}
	return *o.ImsiRanges
}

// GetImsiRangesOk returns a tuple with the ImsiRanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HssInfo) GetImsiRangesOk() (*[]ImsiRange, bool) {
	if o == nil || o.ImsiRanges == nil {
		return nil, false
	}
	return o.ImsiRanges, true
}

// HasImsiRanges returns a boolean if a field has been set.
func (o *HssInfo) HasImsiRanges() bool {
	if o != nil && o.ImsiRanges != nil {
		return true
	}

	return false
}

// SetImsiRanges gets a reference to the given []ImsiRange and assigns it to the ImsiRanges field.
func (o *HssInfo) SetImsiRanges(v []ImsiRange) {
	o.ImsiRanges = &v
}

// GetImsPrivateIdentityRanges returns the ImsPrivateIdentityRanges field value if set, zero value otherwise.
func (o *HssInfo) GetImsPrivateIdentityRanges() []IdentityRange {
	if o == nil || o.ImsPrivateIdentityRanges == nil {
		var ret []IdentityRange
		return ret
	}
	return *o.ImsPrivateIdentityRanges
}

// GetImsPrivateIdentityRangesOk returns a tuple with the ImsPrivateIdentityRanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HssInfo) GetImsPrivateIdentityRangesOk() (*[]IdentityRange, bool) {
	if o == nil || o.ImsPrivateIdentityRanges == nil {
		return nil, false
	}
	return o.ImsPrivateIdentityRanges, true
}

// HasImsPrivateIdentityRanges returns a boolean if a field has been set.
func (o *HssInfo) HasImsPrivateIdentityRanges() bool {
	if o != nil && o.ImsPrivateIdentityRanges != nil {
		return true
	}

	return false
}

// SetImsPrivateIdentityRanges gets a reference to the given []IdentityRange and assigns it to the ImsPrivateIdentityRanges field.
func (o *HssInfo) SetImsPrivateIdentityRanges(v []IdentityRange) {
	o.ImsPrivateIdentityRanges = &v
}

// GetImsPublicIdentityRanges returns the ImsPublicIdentityRanges field value if set, zero value otherwise.
func (o *HssInfo) GetImsPublicIdentityRanges() []IdentityRange {
	if o == nil || o.ImsPublicIdentityRanges == nil {
		var ret []IdentityRange
		return ret
	}
	return *o.ImsPublicIdentityRanges
}

// GetImsPublicIdentityRangesOk returns a tuple with the ImsPublicIdentityRanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HssInfo) GetImsPublicIdentityRangesOk() (*[]IdentityRange, bool) {
	if o == nil || o.ImsPublicIdentityRanges == nil {
		return nil, false
	}
	return o.ImsPublicIdentityRanges, true
}

// HasImsPublicIdentityRanges returns a boolean if a field has been set.
func (o *HssInfo) HasImsPublicIdentityRanges() bool {
	if o != nil && o.ImsPublicIdentityRanges != nil {
		return true
	}

	return false
}

// SetImsPublicIdentityRanges gets a reference to the given []IdentityRange and assigns it to the ImsPublicIdentityRanges field.
func (o *HssInfo) SetImsPublicIdentityRanges(v []IdentityRange) {
	o.ImsPublicIdentityRanges = &v
}

// GetMsisdnRanges returns the MsisdnRanges field value if set, zero value otherwise.
func (o *HssInfo) GetMsisdnRanges() []IdentityRange {
	if o == nil || o.MsisdnRanges == nil {
		var ret []IdentityRange
		return ret
	}
	return *o.MsisdnRanges
}

// GetMsisdnRangesOk returns a tuple with the MsisdnRanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HssInfo) GetMsisdnRangesOk() (*[]IdentityRange, bool) {
	if o == nil || o.MsisdnRanges == nil {
		return nil, false
	}
	return o.MsisdnRanges, true
}

// HasMsisdnRanges returns a boolean if a field has been set.
func (o *HssInfo) HasMsisdnRanges() bool {
	if o != nil && o.MsisdnRanges != nil {
		return true
	}

	return false
}

// SetMsisdnRanges gets a reference to the given []IdentityRange and assigns it to the MsisdnRanges field.
func (o *HssInfo) SetMsisdnRanges(v []IdentityRange) {
	o.MsisdnRanges = &v
}

func (o HssInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.GroupId != nil {
		toSerialize["groupId"] = o.GroupId
	}
	if o.ImsiRanges != nil {
		toSerialize["imsiRanges"] = o.ImsiRanges
	}
	if o.ImsPrivateIdentityRanges != nil {
		toSerialize["imsPrivateIdentityRanges"] = o.ImsPrivateIdentityRanges
	}
	if o.ImsPublicIdentityRanges != nil {
		toSerialize["imsPublicIdentityRanges"] = o.ImsPublicIdentityRanges
	}
	if o.MsisdnRanges != nil {
		toSerialize["msisdnRanges"] = o.MsisdnRanges
	}
	return json.Marshal(toSerialize)
}

type NullableHssInfo struct {
	value *HssInfo
	isSet bool
}

func (v NullableHssInfo) Get() *HssInfo {
	return v.value
}

func (v *NullableHssInfo) Set(val *HssInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableHssInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableHssInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHssInfo(val *HssInfo) *NullableHssInfo {
	return &NullableHssInfo{value: val, isSet: true}
}

func (v NullableHssInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHssInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


