/*
NRF NFDiscovery Service

NRF NFDiscovery Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.2.0-alpha.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ServiceNameAnyOf the model 'ServiceNameAnyOf'
type ServiceNameAnyOf string

// List of ServiceName_anyOf
const (
	NNRF_NFM ServiceNameAnyOf = "nnrf-nfm"
	NNRF_DISC ServiceNameAnyOf = "nnrf-disc"
	NNRF_OAUTH2 ServiceNameAnyOf = "nnrf-oauth2"
	NUDM_SDM ServiceNameAnyOf = "nudm-sdm"
	NUDM_UECM ServiceNameAnyOf = "nudm-uecm"
	NUDM_UEAU ServiceNameAnyOf = "nudm-ueau"
	NUDM_EE ServiceNameAnyOf = "nudm-ee"
	NUDM_PP ServiceNameAnyOf = "nudm-pp"
	NUDM_NIDDAU ServiceNameAnyOf = "nudm-niddau"
	NUDM_MT ServiceNameAnyOf = "nudm-mt"
	NAMF_COMM ServiceNameAnyOf = "namf-comm"
	NAMF_EVTS ServiceNameAnyOf = "namf-evts"
	NAMF_MT ServiceNameAnyOf = "namf-mt"
	NAMF_LOC ServiceNameAnyOf = "namf-loc"
	NSMF_PDUSESSION ServiceNameAnyOf = "nsmf-pdusession"
	NSMF_EVENT_EXPOSURE ServiceNameAnyOf = "nsmf-event-exposure"
	NSMF_NIDD ServiceNameAnyOf = "nsmf-nidd"
	NAUSF_AUTH ServiceNameAnyOf = "nausf-auth"
	NAUSF_SORPROTECTION ServiceNameAnyOf = "nausf-sorprotection"
	NAUSF_UPUPROTECTION ServiceNameAnyOf = "nausf-upuprotection"
	NNEF_PFDMANAGEMENT ServiceNameAnyOf = "nnef-pfdmanagement"
	NNEF_SMCONTEXT ServiceNameAnyOf = "nnef-smcontext"
	NNEF_EVENTEXPOSURE ServiceNameAnyOf = "nnef-eventexposure"
	NPCF_AM_POLICY_CONTROL ServiceNameAnyOf = "npcf-am-policy-control"
	NPCF_SMPOLICYCONTROL ServiceNameAnyOf = "npcf-smpolicycontrol"
	NPCF_POLICYAUTHORIZATION ServiceNameAnyOf = "npcf-policyauthorization"
	NPCF_BDTPOLICYCONTROL ServiceNameAnyOf = "npcf-bdtpolicycontrol"
	NPCF_EVENTEXPOSURE ServiceNameAnyOf = "npcf-eventexposure"
	NPCF_UE_POLICY_CONTROL ServiceNameAnyOf = "npcf-ue-policy-control"
	NSMSF_SMS ServiceNameAnyOf = "nsmsf-sms"
	NNSSF_NSSELECTION ServiceNameAnyOf = "nnssf-nsselection"
	NNSSF_NSSAIAVAILABILITY ServiceNameAnyOf = "nnssf-nssaiavailability"
	NUDR_DR ServiceNameAnyOf = "nudr-dr"
	NUDR_GROUP_ID_MAP ServiceNameAnyOf = "nudr-group-id-map"
	NLMF_LOC ServiceNameAnyOf = "nlmf-loc"
	N5G_EIR_EIC ServiceNameAnyOf = "n5g-eir-eic"
	NBSF_MANAGEMENT ServiceNameAnyOf = "nbsf-management"
	NCHF_SPENDINGLIMITCONTROL ServiceNameAnyOf = "nchf-spendinglimitcontrol"
	NCHF_CONVERGEDCHARGING ServiceNameAnyOf = "nchf-convergedcharging"
	NCHF_OFFLINEONLYCHARGING ServiceNameAnyOf = "nchf-offlineonlycharging"
	NNWDAF_EVENTSSUBSCRIPTION ServiceNameAnyOf = "nnwdaf-eventssubscription"
	NNWDAF_ANALYTICSINFO ServiceNameAnyOf = "nnwdaf-analyticsinfo"
	NNWDAF_DATAMANAGEMENT ServiceNameAnyOf = "nnwdaf-datamanagement"
	NNWDAF_MLMODELPROVISION ServiceNameAnyOf = "nnwdaf-mlmodelprovision"
	NGMLC_LOC ServiceNameAnyOf = "ngmlc-loc"
	NUCMF_PROVISIONING ServiceNameAnyOf = "nucmf-provisioning"
	NUCMF_UECAPABILITYMANAGEMENT ServiceNameAnyOf = "nucmf-uecapabilitymanagement"
	NHSS_SDM ServiceNameAnyOf = "nhss-sdm"
	NHSS_UECM ServiceNameAnyOf = "nhss-uecm"
	NHSS_UEAU ServiceNameAnyOf = "nhss-ueau"
	NHSS_EE ServiceNameAnyOf = "nhss-ee"
	NHSS_IMS_SDM ServiceNameAnyOf = "nhss-ims-sdm"
	NHSS_IMS_UECM ServiceNameAnyOf = "nhss-ims-uecm"
	NHSS_IMS_UEAU ServiceNameAnyOf = "nhss-ims-ueau"
	NSEPP_TELESCOPIC ServiceNameAnyOf = "nsepp-telescopic"
	NSORAF_SOR ServiceNameAnyOf = "nsoraf-sor"
	NSPAF_SECURED_PACKET ServiceNameAnyOf = "nspaf-secured-packet"
	NUDSF_DR ServiceNameAnyOf = "nudsf-dr"
	NUDSF_TIMER ServiceNameAnyOf = "nudsf-timer"
	NNSSAAF_NSSAA ServiceNameAnyOf = "nnssaaf-nssaa"
	NAANF_AKMA ServiceNameAnyOf = "naanf-akma"
	N5GDDNMF_DISCOVERY ServiceNameAnyOf = "n5gddnmf-discovery"
	NMFAF_3DADM ServiceNameAnyOf = "nmfaf-3dadm"
	NMFAF_3CADM ServiceNameAnyOf = "nmfaf-3cadm"
	NEASDF_DNSCONTEXT ServiceNameAnyOf = "neasdf-dnscontext"
	NDCCF_DM ServiceNameAnyOf = "ndccf-dm"
	NDCCF_CM ServiceNameAnyOf = "ndccf-cm"
	NNSACF_NSAC ServiceNameAnyOf = "nnsacf-nsac"
	NNSACF_SLICE_EE ServiceNameAnyOf = "nnsacf-slice-ee"
	NMBSMF_TMGI ServiceNameAnyOf = "nmbsmf-tmgi"
	NMBSMF_MBSSESSION ServiceNameAnyOf = "nmbsmf-mbssession"
	NMBSMF_RECEPTION ServiceNameAnyOf = "nmbsmf-reception"
	NMBSMF_INFORMATION ServiceNameAnyOf = "nmbsmf-information"
	NADRF_DM ServiceNameAnyOf = "nadrf-dm"
	NBSP_GBA ServiceNameAnyOf = "nbsp-gba"
)

var allowedServiceNameAnyOfEnumValues = []ServiceNameAnyOf{
	"nnrf-nfm",
	"nnrf-disc",
	"nnrf-oauth2",
	"nudm-sdm",
	"nudm-uecm",
	"nudm-ueau",
	"nudm-ee",
	"nudm-pp",
	"nudm-niddau",
	"nudm-mt",
	"namf-comm",
	"namf-evts",
	"namf-mt",
	"namf-loc",
	"nsmf-pdusession",
	"nsmf-event-exposure",
	"nsmf-nidd",
	"nausf-auth",
	"nausf-sorprotection",
	"nausf-upuprotection",
	"nnef-pfdmanagement",
	"nnef-smcontext",
	"nnef-eventexposure",
	"npcf-am-policy-control",
	"npcf-smpolicycontrol",
	"npcf-policyauthorization",
	"npcf-bdtpolicycontrol",
	"npcf-eventexposure",
	"npcf-ue-policy-control",
	"nsmsf-sms",
	"nnssf-nsselection",
	"nnssf-nssaiavailability",
	"nudr-dr",
	"nudr-group-id-map",
	"nlmf-loc",
	"n5g-eir-eic",
	"nbsf-management",
	"nchf-spendinglimitcontrol",
	"nchf-convergedcharging",
	"nchf-offlineonlycharging",
	"nnwdaf-eventssubscription",
	"nnwdaf-analyticsinfo",
	"nnwdaf-datamanagement",
	"nnwdaf-mlmodelprovision",
	"ngmlc-loc",
	"nucmf-provisioning",
	"nucmf-uecapabilitymanagement",
	"nhss-sdm",
	"nhss-uecm",
	"nhss-ueau",
	"nhss-ee",
	"nhss-ims-sdm",
	"nhss-ims-uecm",
	"nhss-ims-ueau",
	"nsepp-telescopic",
	"nsoraf-sor",
	"nspaf-secured-packet",
	"nudsf-dr",
	"nudsf-timer",
	"nnssaaf-nssaa",
	"naanf-akma",
	"n5gddnmf-discovery",
	"nmfaf-3dadm",
	"nmfaf-3cadm",
	"neasdf-dnscontext",
	"ndccf-dm",
	"ndccf-cm",
	"nnsacf-nsac",
	"nnsacf-slice-ee",
	"nmbsmf-tmgi",
	"nmbsmf-mbssession",
	"nmbsmf-reception",
	"nmbsmf-information",
	"nadrf-dm",
	"nbsp-gba",
}

func (v *ServiceNameAnyOf) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ServiceNameAnyOf(value)
	for _, existing := range allowedServiceNameAnyOfEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ServiceNameAnyOf", value)
}

// NewServiceNameAnyOfFromValue returns a pointer to a valid ServiceNameAnyOf
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewServiceNameAnyOfFromValue(v string) (*ServiceNameAnyOf, error) {
	ev := ServiceNameAnyOf(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ServiceNameAnyOf: valid values are %v", v, allowedServiceNameAnyOfEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ServiceNameAnyOf) IsValid() bool {
	for _, existing := range allowedServiceNameAnyOfEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ServiceName_anyOf value
func (v ServiceNameAnyOf) Ptr() *ServiceNameAnyOf {
	return &v
}

type NullableServiceNameAnyOf struct {
	value *ServiceNameAnyOf
	isSet bool
}

func (v NullableServiceNameAnyOf) Get() *ServiceNameAnyOf {
	return v.value
}

func (v *NullableServiceNameAnyOf) Set(val *ServiceNameAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceNameAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceNameAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceNameAnyOf(val *ServiceNameAnyOf) *NullableServiceNameAnyOf {
	return &NullableServiceNameAnyOf{value: val, isSet: true}
}

func (v NullableServiceNameAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceNameAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

