/*
NRF NFDiscovery Service

NRF NFDiscovery Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.2.0-alpha.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DnnTsctsfInfoItem Parameters supported by an TSCTSF for a given DNN
type DnnTsctsfInfoItem struct {
	Dnn AnyOfstringstring `json:"dnn"`
}

// NewDnnTsctsfInfoItem instantiates a new DnnTsctsfInfoItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDnnTsctsfInfoItem(dnn AnyOfstringstring) *DnnTsctsfInfoItem {
	this := DnnTsctsfInfoItem{}
	this.Dnn = dnn
	return &this
}

// NewDnnTsctsfInfoItemWithDefaults instantiates a new DnnTsctsfInfoItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDnnTsctsfInfoItemWithDefaults() *DnnTsctsfInfoItem {
	this := DnnTsctsfInfoItem{}
	return &this
}

// GetDnn returns the Dnn field value
func (o *DnnTsctsfInfoItem) GetDnn() AnyOfstringstring {
	if o == nil {
		var ret AnyOfstringstring
		return ret
	}

	return o.Dnn
}

// GetDnnOk returns a tuple with the Dnn field value
// and a boolean to check if the value has been set.
func (o *DnnTsctsfInfoItem) GetDnnOk() (*AnyOfstringstring, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Dnn, true
}

// SetDnn sets field value
func (o *DnnTsctsfInfoItem) SetDnn(v AnyOfstringstring) {
	o.Dnn = v
}

func (o DnnTsctsfInfoItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["dnn"] = o.Dnn
	}
	return json.Marshal(toSerialize)
}

type NullableDnnTsctsfInfoItem struct {
	value *DnnTsctsfInfoItem
	isSet bool
}

func (v NullableDnnTsctsfInfoItem) Get() *DnnTsctsfInfoItem {
	return v.value
}

func (v *NullableDnnTsctsfInfoItem) Set(val *DnnTsctsfInfoItem) {
	v.value = val
	v.isSet = true
}

func (v NullableDnnTsctsfInfoItem) IsSet() bool {
	return v.isSet
}

func (v *NullableDnnTsctsfInfoItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDnnTsctsfInfoItem(val *DnnTsctsfInfoItem) *NullableDnnTsctsfInfoItem {
	return &NullableDnnTsctsfInfoItem{value: val, isSet: true}
}

func (v NullableDnnTsctsfInfoItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDnnTsctsfInfoItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


